apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres
spec:
  version: "9.6-v2"
  replicas: 2
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi


